### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be one of type string or Buffer. Received type undefined

### ISSUE THREAD

**Issue by SalathielGenese** [jas-/kruptein#1]
**Stacktrace**

```
(node:22642) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be one of type string or Buffer. Received type undefined
    at validChunk (_stream_writable.js:263:10)
    at Hmac.Writable.write (_stream_writable.js:297:21)
    at kruptein._digest (${PROJECT_ROOT}/node_modules/kruptein/lib/kruptein.js:175:10)
    at kruptein.get (${PROJECT_ROOT}/node_modules/kruptein/lib/kruptein.js:69:17)
    at getSession (${PROJECT_ROOT}/src/router/session.js:64:31)
    at authMiddeware (${PROJECT_ROOT}/src/router/session.js:27:21)
    at Layer.handle [as handle_request] (${PROJECT_ROOT}/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (${PROJECT_ROOT}/node_modules/express/lib/router/index.js:317:13)
    at ${PROJECT_ROOT}/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (${PROJECT_ROOT}/node_modules/express/lib/router/index.js:335:12)
    at next (${PROJECT_ROOT}/node_modules/express/lib/router/index.js:275:10)
    at expressInit (${PROJECT_ROOT}/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (${PROJECT_ROOT}/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (${PROJECT_ROOT}/node_modules/express/lib/router/index.js:317:13)
    at ${PROJECT_ROOT}/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (${PROJECT_ROOT}/node_modules/express/lib/router/index.js:335:12)
    at next (${PROJECT_ROOT}/node_modules/express/lib/router/index.js:275:10)
    at query (${PROJECT_ROOT}/node_modules/express/lib/middleware/query.js:45:5)
    at Layer.handle [as handle_request] (${PROJECT_ROOT}/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (${PROJECT_ROOT}/node_modules/express/lib/router/index.js:317:13)
    at ${PROJECT_ROOT}/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (${PROJECT_ROOT}/node_modules/express/lib/router/index.js:335:12)
```

**Suggested fix**

https://github.com/jas-/kruptein/blob/master/lib/kruptein.js#L69

From :

```
    hmac = this._digest(this.secret, ct.ct, this.hashing, this.encodeas)
    //                                 ^^^
```

To :

```
    hmac = this._digest(this.secret, ct, this.hashing, this.encodeas)
```

**Comment by jas-** [comment]
Use case please? It helps if you provide an example code that is triggering the error. The plAintext value passed much be a valid strong or buffer

**Comment by SalathielGenese** [comment]
Sorry, I hit `Ctrl + Enter` as if I was on Slack.
Check now, I edited

**Comment by SalathielGenese** [comment]
Though I suggest something, I want to mention that I am no expert at it.

I use it for stateless session management with HTTP cookies.

```
const setSession = ( session, response ) => {
    session.last = Date.now();

    const text = JSON.stringify( session );
    const hash = kruptein.set( text );
    const base64 = Buffer.from( hash ).toString( 'base64' );

    response.cookie( SESSION_COOKIE_NAME, base64, { maxAge: SESSION_LIFETIME });
};

const getSession = request => {
    const base64 = ( request.headers.cookie || '' ).replace(
        new RegExp( `${ SESSION_COOKIE_NAME }=([^;]+)` ), '$1' );

    if ( base64 ) {
        const hash = Buffer.from( base64, 'base64' ).toString();
        console.log( '++++++++++++++++++++++++++++++++++++++++++++++++' );
        console.log( hash );
        const text = kruptein.get( hash );
        const json = JSON.parse( text );

        return JSON.parse( json );
    }
};
```

I later call `getSession` from my middleware -
But see the log right before error

```
++++++++++++++++++++++++++++++++++++++++++++++++
{"hmac":"æ·}æîùò7ç)ø¨ °¢!³6ì\u0007\"4h\u0016p\n\r|V\u0005¶�q�����g���G
��
�\(�<(,9L+aI��p��L

                  M��W������p����0��L
�                                              ]H���M
 MM�                                 L0�0�p��Än
�   �K

�KM�
  ��K
     L
L�
� M
 ��
NK
  �
   �
    �
     �

      L�W__Cp�
```
And here is the `base64` value -
```
eyJobWFjIjoiw6bCt8KQP8KxLcKVfcOmw67DucOyN8OnKcO4wqggwrDCoiHCszbDrMKWXHUwMDA3XCLCizRoXHUwMDE2cFxuXHJ8Vlx1MDAwNcK%2FNVx1MDAxNMOZw6LDtjJRwrHDpcK%2Fwo5DwoLDlMK%2FJHfDncK8S1x1MDAxN0tUeVxuwociLCJjdCI6IsOsYcKaXGbDnMKTXHUwMDEww5zChcK%2Fw4Ruwo3CmE%2FDhcO3XHUwMDBlXHUwMDEyXHUwMDFiw5nDu0fDki5jwqtrOcK%2BK8OFcyXCq8KPwrzCh8KZLFbCpk8zVMKTXHUwMDBmw4pew7Rvw4hRPVx1MDAxYcKRw53DucOgKVx1MDAxOcKia8Ksw4UxZcKuwqfDu8O5wqRIw4PCmMKQSMOIXG4iLCJpdiI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6WzEwMSwyMiwxMzMsMTE0LDMyLDIwNyw4NywyMjUsNTMsNzksMTMsMTg1XX0sImFhZCI6IsOGwqhcZlvCgXAqw7NccsKmw7A7XHUwMDA1wp3Dqlx1MDAwZlx0XzFfw4nDkm9qwo7DvEo9wrPDjsO%2Fw6U4w516dcOLw6lBXHUwMDFhS2bDvmDCg8OdL8OpXHUwMDFhRFx1MDAxMyfCj8KIXHUwMDFiw5nChFx1MDAwMHTDosKLQ8KKw4UiLCJhdCI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6WzE0NywxNTcsMjQ5LDY4LDE1Niw2NSwyMzksMTA4LDUzLDE0NiwyMzAsNTksMywyMDMsMjA4LDEyOV19fQ%3D%3D
```

**Comment by SalathielGenese** [comment]
Maybe the right question/concern would be, how to serialize `kruptein.get` result ?

**Comment by jas-** [comment]
Have you looked at the [vanilla](https://github.com/jas-/kruptein/blob/master/.test/vanilla.js) test case?

The module returns an object which if you are storing in some database or flat file for session middleware should be serialized / deserialized.

**Comment by SalathielGenese** [comment]
Hello @jas- ,

I found the bug -
Cookies are URL encoded.
That's what I was missing...

I'm sorry that I didn't find it before opening this issue.
Thank you for looking into it. I appreciate your spontaneity.
